apiVersion: v1
kind: Service
metadata:
  name: notesapp-be-service
  namespace: notesapp
spec:
  selector:
    app: notesapp-be
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
