apiVersion: v1
kind: Service
metadata:
  name: notesapp-fe-service
  namespace: notesapp
spec:
  selector:
    app: notesapp-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
