apiVersion: v1
kind: Secret
metadata:
  name: notesapp-db-secrets
  namespace: notesapp
type: Opaque
data:
  POSTGRES_DB: bm90ZXNhcHBkYg==
  POSTGRES_USER: bm90ZXNhcHB1c2Vy
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
